# Inherit the same environment as the root SConstruct 
Import('env')

# Create paths relative to the current directory
env.Append(CPPPATH = [
    '.',
    'core',
    'loggers',
    'metrics',
    'storage',
])

env.Library(
    target = 'logging',
    source = [
        # Storage
        'storage/selection/selection_storage.cc',
        'storage/timing/timing_storage.cc',
        'storage/replacement/replacement_storage.cc',
        'storage/removal/removal_storage.cc',
        
        # Core
        'core/event_dispatcher.tpp',
        
        # Loggers
        'loggers/selection/selection_logger.cc',
        'loggers/timing/timing_logger.cc',
        'loggers/replacement/replacement_logger.cc',
        'loggers/removal/removal_logger.cc',
        
        # Metrics
        'metrics/selection/selection_metrics.cc',
        'metrics/selection/selection_metrics_builder.cc',
        'metrics/timing/timing_metrics.cc',
        'metrics/timing/timing_metrics_builder.cc',
        'metrics/replacement/replacement_metrics_builder.cc',
        'metrics/removal/removal_metrics_builder.cc',
    ],
    CPPPATH = ['.']
)

env.Append(CPPPATH = [env.Dir('.')])
