# Inherit the same environment as the root SConstruct 
Import('env')

# Create paths relative to the current directory
env.Append(CPPPATH = [
    '.',
    'core',
    'loggers',
    'metrics',
    'storage',
])

env.Library(
    target = 'logging',
    source = [
        # Storage
        'storage/mta/mta_storage.cc',
        'storage/tms/timing_storage.cc',
        
        # Core
        'core/event_dispatcher.tpp',
        
        # Loggers
        'loggers/mta/mta_logger.cc',
        'loggers/tms/timing_logger.cc',
        
        # Metrics
        'metrics/mta/mta_metrics.cc',
        'metrics/mta/mta_metrics_builder.cc',
        'metrics/tms/timing_metrics.cc',
        'metrics/tms/timing_metrics_builder.cc' 
    ],
    CPPPATH = ['.']
)

env.Append(CPPPATH = [env.Dir('.')])
